### ISSUE TITLE
undefined method 'text' for messages.

### ISSUE THREAD

**Issue by jasonhazel** [obrie/turntabler#1]
Trying out some of the examples, i'm running into an error in regards to chat messages.  The following error happens anytime a chat message is received.

```
D, [2012-12-17T20:28:08.103050 #7405] DEBUG -- : Message received: {"command"=>"speak", "userid"=>"4e279f00a3f75124550495b5", "name"=>"equirk.ogg", "roomid"=>"50c8ea562e3817160a05b31c", "text"=>"testf"}
E, [2012-12-17T20:28:08.103589 #7405] ERROR -- : undefined method `text' for #<Turntabler::Message:0x00000001786148 @content="testf">
./chat_bot.rb:12:in `block (2 levels) in <main>'
/home/jason/.rvm/gems/ruby-1.9.2-p318/gems/turntabler-0.1.2/lib/turntabler/handler.rb:51:in `call'
/home/jason/.rvm/gems/ruby-1.9.2-p318/gems/turntabler-0.1.2/lib/turntabler/handler.rb:51:in `block in run'
/home/jason/.rvm/gems/ruby-1.9.2-p318/gems/turntabler-0.1.2/lib/turntabler/handler.rb:49:in `each'
/home/jason/.rvm/gems/ruby-1.9.2-p318/gems/turntabler-0.1.2/lib/turntabler/handler.rb:49:in `run'
/home/jason/.rvm/gems/ruby-1.9.2-p318/gems/turntabler-0.1.2/lib/turntabler/client.rb:453:in `block in on_message'
/home/jason/.rvm/gems/ruby-1.9.2-p318/gems/turntabler-0.1.2/lib/turntabler/client.rb:452:in `each'
/home/jason/.rvm/gems/ruby-1.9.2-p318/gems/turntabler-0.1.2/lib/turntabler/client.rb:452:in `on_message'
/home/jason/.rvm/gems/ruby-1.9.2-p318/gems/turntabler-0.1.2/lib/turntabler/client.rb:102:in `block in connect'
/home/jason/.rvm/gems/ruby-1.9.2-p318/gems/turntabler-0.1.2/lib/turntabler/connection.rb:130:in `call'
/home/jason/.rvm/gems/ruby-1.9.2-p318/gems/turntabler-0.1.2/lib/turntabler/connection.rb:130:in `block in dispatch'
/home/jason/.rvm/gems/ruby-1.9.2-p318/gems/turntabler-0.1.2/lib/turntabler.rb:89:in `call'
/home/jason/.rvm/gems/ruby-1.9.2-p318/gems/turntabler-0.1.2/lib/turntabler.rb:89:in `block (2 levels) in run'
/home/jason/.rvm/gems/ruby-1.9.2-p318/gems/em-synchrony-1.0.2/lib/em-synchrony.rb:26:in `call'
/home/jason/.rvm/gems/ruby-1.9.2-p318/gems/em-synchrony-1.0.2/lib/em-synchrony.rb:26:in `block (2 levels) in synchrony'
```

The other examples that I have tried are working, but any that use messages seem to be throwing this error.

**Comment by jasonhazel** [comment]
Replacing `message.text` with `message.content` in the example seems to have done the trick.

**Comment by obrie** [comment]
Good catch!  I'll look into fixing the examples to avoid confusion for others.
