### ISSUE TITLE
@client.start doesn't exist

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#12]
Hi based on my previous reports i've been trying to get two threads to work independently and based off the example here: http://rdoc.info/github/obrie/turntabler/master/Turntabler.interactive I have built a very simple test and i'm getting an error that start doesn't exist.   

---
# !/usr/bin/ruby

require 'turntabler'
require 'monitor'
require 'eventmachine'

require 'rubygems'
require 'nokogiri'
require 'open-uri'
# Constants

EMAIL           = ''                               # 'xxxxx@xxxxx.com'
PASSWORD        = ''                               # 'xxxxx'
ROOM            = '50b9c49faaa5cd76060cdb84'       # Pur your roomid here
USER_ID         = '5098bb36eb35c15965691ada'
AUTH            = ''

Turntabler.interactive
Turntabler.run do
  @client = Turntabler::Client.new(EMAIL, PASSWORD, :room => ROOM, :user_id => USER_ID, :auth => AUTH, :reconnect => true, :reconnect_wait => 60)
  @client.start
  while 1 do
        @client.room.say("Hi from main thread")
        sleep(10)
        end
end

Turntabler.run do
  @client.user.load
  while 1 do
        @client.room.say("Hi from other thread")
        sleep(10)
        end
  # ...
end

---

D, [2013-01-10T22:55:37.423590 #20758] DEBUG -- : Socket opened
D, [2013-01-10T22:55:37.529678 #20758] DEBUG -- : Message received: {"command"=>"no_session"}
D, [2013-01-10T22:55:37.530330 #20758] DEBUG -- : Message sent: {:clientid=>"1357887336-0.5803664622247058", :userid=>"5098bb36eb35c15965691ada", :userauth=>"", :api=>"user.authenticate", :msgid=>1}
D, [2013-01-10T22:55:37.690738 #20758] DEBUG -- : Message received: {"msgid"=>1, "success"=>true, "command"=>"response_received"}
D, [2013-01-10T22:55:37.691494 #20758] DEBUG -- : Message sent: {:clientid=>"1357887336-0.5803664622247058", :userid=>"5098bb36eb35c15965691ada", :userauth=>"", :api=>"user.get_fan_of", :msgid=>2}
D, [2013-01-10T22:55:37.850750 #20758] DEBUG -- : Message received: {"msgid"=>2, "fanof"=>["4f4e36cda3f7517d7500174c", "4ea8d05fa3f751271d024366", "4e6fda31a3f75112c7085798", "4faf6253eb35c11f2200045c"], "success"=>true, "command"=>"response_received"}
D, [2013-01-10T22:55:37.851439 #20758] DEBUG -- : Message sent: {:clientid=>"1357887336-0.5803664622247058", :userid=>"5098bb36eb35c15965691ada", :userauth=>"", :status=>"available", :api=>"presence.update", :msgid=>3}
D, [2013-01-10T22:55:38.004497 #20758] DEBUG -- : Message received: {"msgid"=>3, "now"=>1357887371.43, "success"=>true, "interval"=>10, "command"=>"response_received"}
D, [2013-01-10T22:55:38.005364 #20758] DEBUG -- : Message sent: {:clientid=>"1357887336-0.5803664622247058", :userid=>"5098bb36eb35c15965691ada", :userauth=>"", :section=>nil, :roomid=>"50b9c49faaa5cd76060cdb84", :api=>"room.register", :msgid=>4}
D, [2013-01-10T22:55:38.202491 #20758] DEBUG -- : Message received: {"command"=>"registered", "roomid"=>"50b9c49faaa5cd76060cdb84", "user"=>[{"name"=>"Terence McKenna", "laptop_version"=>nil, "laptop"=>"linux", "created"=>1352186678.98, "userid"=>"5098bb36eb35c15965691ada", "acl"=>0, "fans"=>11, "points"=>472, "images"=>{"fullfront"=>"/roommanager_assets/avatars/10/fullfront.png", "headfront"=>"/roommanager_assets/avatars/10/headfront.png"}, "_id"=>"5098bb36eb35c15965691ada", "avatarid"=>10}], "success"=>true}
D, [2013-01-10T22:55:38.203744 #20758] DEBUG -- : Message sent: {:clientid=>"1357887336-0.5803664622247058", :userid=>"5098bb36eb35c15965691ada", :userauth=>"", :extended=>false, :roomid=>"50b9c49faaa5cd76060cdb84", :section=>nil, :api=>"room.info", :msgid=>5}
D, [2013-01-10T22:55:38.316893 #20758] DEBUG -- : Message received: {"msgid"=>4, "section"=>nil, "roomid"=>"50b9c49faaa5cd76060cdb84", "success"=>true, "command"=>"response_received"}
E, [2013-01-10T22:55:38.319694 #20758] ERROR -- : undefined method `start' for #<Turntabler::Client:0x000000029f5c70>
./IPCTest.rb:22:in`block in <main>'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler.rb:89:in `call'
/var/lib/gems/1.9.1/gems/turntabler-0.1.4/lib/turntabler.rb:89:in`block (2 levels) in run'
/var/lib/gems/1.9.1/gems/em-synchrony-1.0.2/lib/em-synchrony.rb:26:in `call'
/var/lib/gems/1.9.1/gems/em-synchrony-1.0.2/lib/em-synchrony.rb:26:in`block (2 levels) in synchrony'

**Comment by StephanieSunshine** [comment]
Ok I think I figured out a solution to my problem:

```
 #!/usr/bin/ruby

 require 'turntabler'
 require 'eventmachine'

 # Constants
 EMAIL = ''           # 'xxxxx@xxxxx.com'
 PASSWORD = ''  # 'xxxxx'
 ROOM = ''           # Put your roomid here
 USER_ID = ''       # Bots userid
 AUTH = ''            # Bots authid

 Turntabler.interactive
 client = nil  #i'm not sure i have to do this now

 Turntabler.run do
     client = Turntabler::Client.new(EMAIL, PASSWORD, :room => ROOM, :user_id => USER_ID, :auth => AUTH, :reconnect => true, :reconnect_wait => 60)
 # Periodic timer example
     EventMachine::PeriodicTimer.new(60) do
          Turntabler.run { client.room.say "Hug your local developer" }
          end
 # Single timer example
     EventMachine::Timer.new(60) do
          Turntabler.run { client.room.say "Hug your local developer" }
          end
 # Add the rest of your code here
     end
```

I hope this helps someone, if you would like to add something like this to your examples, feel free to copy anything I wrote. :)
